### ISSUE TITLE
Rename to mapbox-mapmatch?

### ISSUE THREAD

**Issue by freenerd** [mapbox/mapbox-mapmatch#1]
Since this is tied tightly to the Mapbox API and similar to [mapbox-directions](https://github.com/mapbox/mapbox-directions.js), should we rename it to mapbox-mapmatch?

/cc @aaronlidman

**Comment by planemad** [comment]
@aaronlidman @freenerd 

Makes sense, i'm going to rename the repo. Brace yourself :seat:

**Comment by freenerd** [comment]
Boom done. Locally you'll need to fix your origin:

```
git remote rm origin
git remote add origin git@github.com:mapbox/mapbox-mapmatch.git
```
