### ISSUE TITLE
Consider using polylines

### ISSUE THREAD

**Issue by freenerd** [mapbox/mapbox-mapmatch#5]
[Polylines](https://www.mapbox.com/mapbox.js/example/v1.0.0/polyline/) will be faster to transfer, since they are way smaller. You can request them via `?geometry=polyline`.

**Comment by planemad** [comment]
@freenerd currently mapmatching API returns an error if ccordTimes is not present, how would these be stored in the polylines?

**Comment by planemad** [comment]
@freenerd 
> https://api-directions-johan-matching.tilestream.net/matching/v4/mapbox.driving.json?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ?geometry=polyline

Gives me: {"message":"Invalid Access Token"}

**Comment by freenerd** [comment]
`&geometry`

**Comment by planemad** [comment]
@freenerd :+1:

**Comment by planemad** [comment]
@freenerd sample polyline response
> {"geometry":"m~keiAjlj|qCkI@iAAqB@eE@yAAqOBeH@eL@gWFqB?mFOc@BqDAaDIyCA}ACuC@{MAqH@wJ@aL@qKB_K@eHAo@@sBAuD@cA?oI?uJ?eK?cK?oK?qK?oNFoC?iD@kECsLD{FBmJ?{J?]A?aa@qSRkDD@wQ"}

Which seems invalid according to https://developers.google.com/maps/documentation/utilities/polylineutility

Decoding using mapbox-polyline I get http://pastebin.com/sSEvRw08

Everything works ok without the polyline request

**Comment by aaronlidman** [comment]
@planemad Try `polyline.decode(polyline, 6)`

By default, out polyline lib is not compatible with google's format. Precision is 5, instead of google's 6.

**Comment by planemad** [comment]
Thanks @aaronlidman this one was quite a :ferris_wheel:
